(() => {
'use strict';
const rasterStyle={version:8,sources:{osm:{type:'raster',tiles:['https://tile.openstreetmap.org/{z}/{x}/{y}.png'],tileSize:256,attribution:'© OpenStreetMap contributors'}},layers:[{id:'osm',type:'raster',source:'osm'}]};
let map=null,ready=false,pending=[];
const valid=p=>p&&Number.isFinite(Number(p.lon))&&Number.isFinite(Number(p.lat));
function routeFeature(a){const pts=(a.routePoints||[]).filter(valid);if(pts.length<2)return null;return{type:'Feature',properties:{id:a.id,title:a.title,status:a.status||'completed'},geometry:{type:'LineString',coordinates:pts.map(p=>[Number(p.lon),Number(p.lat)])}}}
function pointFeatures(a){const out=[];if(valid(a.startCoord))out.push({type:'Feature',properties:{id:a.id,title:a.title,kind:'start',status:a.status||'completed'},geometry:{type:'Point',coordinates:[Number(a.startCoord.lon),Number(a.startCoord.lat)]}});if(valid(a.endCoord)&&(!a.startCoord||a.endCoord.lat!==a.startCoord.lat||a.endCoord.lon!==a.startCoord.lon))out.push({type:'Feature',properties:{id:a.id,title:a.title,kind:'finish',status:a.status||'completed'},geometry:{type:'Point',coordinates:[Number(a.endCoord.lon),Number(a.endCoord.lat)]}});return out}
function routeData(rows){return{type:'FeatureCollection',features:rows.map(routeFeature).filter(Boolean)}}function pointData(rows){return{type:'FeatureCollection',features:rows.flatMap(pointFeatures)}}
function boundsFor(rows){const coords=[];rows.forEach(a=>{(a.routePoints||[]).forEach(p=>valid(p)&&coords.push([Number(p.lon),Number(p.lat)]));if(valid(a.startCoord))coords.push([Number(a.startCoord.lon),Number(a.startCoord.lat)]);if(valid(a.endCoord))coords.push([Number(a.endCoord.lon),Number(a.endCoord.lat)])});return coords}
function draw(rows){pending=rows||[];if(!map||!ready)return;map.getSource('world-routes')?.setData(routeData(pending));map.getSource('world-points')?.setData(pointData(pending));const coords=boundsFor(pending);if(coords.length){const b=coords.reduce((x,c)=>x.extend(c),new maplibregl.LngLatBounds(coords[0],coords[0]));map.fitBounds(b,{padding:70,maxZoom:11,duration:500})}}
function select(id){if(!map||!ready)return;map.setFilter('world-route-active',['==',['get','id'],String(id||'')]);const a=pending.find(x=>String(x.id)===String(id));if(!a)return;const coords=boundsFor([a]);if(coords.length>1){const b=coords.reduce((x,c)=>x.extend(c),new maplibregl.LngLatBounds(coords[0],coords[0]));map.fitBounds(b,{padding:90,maxZoom:12,duration:450});}else if(coords[0])map.easeTo({center:coords[0],zoom:10,duration:400})}
function init(container,rows=[]){if(map){draw(rows);return map}if(!container||typeof maplibregl==='undefined')return null;pending=rows;map=new maplibregl.Map({container,style:rasterStyle,center:[-3.2,54.7],zoom:4.5,minZoom:3.2,maxZoom:17});map.addControl(new maplibregl.NavigationControl({showCompass:false}),'top-right');map.addControl(new maplibregl.ScaleControl({unit:'metric'}));map.on('load',()=>{ready=true;map.addSource('world-routes',{type:'geojson',data:routeData(pending)});map.addSource('world-points',{type:'geojson',data:pointData(pending)});map.addLayer({id:'world-routes',type:'line',source:'world-routes',paint:{'line-color':['case',['==',['get','status'],'planned'],'#8ca5ad','#f08a35'],'line-width':['case',['==',['get','status'],'planned'],3,4],'line-opacity':['case',['==',['get','status'],'planned'],.55,.9]}});map.addLayer({id:'world-route-active',type:'line',source:'world-routes',filter:['==',['get','id'],''],paint:{'line-color':'#ffffff','line-width':7,'line-opacity':.55}});map.addLayer({id:'world-points',type:'circle',source:'world-points',paint:{'circle-color':['case',['==',['get','kind'],'start'],'#ffffff','#f08a35'],'circle-radius':['case',['==',['get','kind'],'start'],6,8],'circle-stroke-color':'#172125','circle-stroke-width':2}});const click=e=>{const f=e.features?.[0];if(f)window.dispatchEvent(new CustomEvent('adventurehub:open',{detail:{id:f.properties.id}}))};map.on('click','world-routes',click);map.on('click','world-points',click);['world-routes','world-points'].forEach(l=>{map.on('mouseenter',l,()=>map.getCanvas().style.cursor='pointer');map.on('mouseleave',l,()=>map.getCanvas().style.cursor='')});draw(pending)});return map}
window.AdventureHubMap={init,draw,select,resize:()=>map?.resize()};
})();
