(() => {
'use strict';
const root=document.querySelector('[data-adventure-hub]'),store=window.AdventureHubStore;if(!root||!store)return;
const $=(s,c=root)=>c.querySelector(s),esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const meta={hike:['🥾','Hike'],cycle:['🚴','Cycle'],road:['🚐','Road trip'],camp:['🏕️','Camping'],paddle:['🏄','Paddleboard'],kayak:['🛶','Kayak'],explore:['🧭','Explore']};
const icon=t=>meta[t]?.[0]||'🧭',label=t=>meta[t]?.[1]||'Adventure';
const niceDate=s=>{if(!s)return'Date not set';const d=new Date(`${String(s).slice(0,10)}T12:00:00`);return Number.isNaN(d)?s:d.toLocaleDateString('en-GB',{day:'numeric',month:'short',year:'numeric'})};
const km=n=>`${(Number(n)||0).toFixed(Number(n)<10?1:0)} km`;
const mins=n=>{n=Math.max(0,Math.round(Number(n)||0));const h=Math.floor(n/60),m=n%60;return h?`${h}h ${m?`${m}m`:''}`.trim():`${m} min`};
function nextCard(){const a=store.next(),host=$('[data-next-adventure]');if(!a){host.innerHTML=`<div><p class="abh-kicker">Your next adventure</p><h2>Nothing planned yet</h2><p class="abh-muted">Find somewhere new, build the trip, then it will appear here ready to continue.</p></div><div class="abh-next-actions"><a class="abh-btn primary" href="adventure-finder.html">Find an adventure</a><a class="abh-btn" href="trip-planner.html">Plan a trip</a></div>`;return}host.innerHTML=`<div><p class="abh-kicker">Your next adventure</p><h2>${esc(a.title)}</h2><div class="abh-next-route"><span></span><strong>${esc(a.startName||'Start')}</strong><i></i><strong>${esc(a.endName||'Destination')}</strong></div><div class="abh-next-meta"><span class="abh-chip">📅 ${niceDate(a.date)}</span>${a.days?`<span class="abh-chip">🗓 ${a.days} day${a.days===1?'':'s'}</span>`:''}${a.stops?`<span class="abh-chip">📍 ${a.stops} planned stop${a.stops===1?'':'s'}</span>`:''}${a.distanceKm?`<span class="abh-chip">🛣 ${km(a.distanceKm)}</span>`:''}</div></div><div class="abh-next-actions"><a class="abh-btn primary" href="${a.source==='walking'?'walking-hiking.html':a.source==='paddle'?'paddling.html':'trip-planner.html'}">Continue planning</a><a class="abh-btn" href="https://app.adventurebuilder.co.uk" target="_blank" rel="noopener">Open in app</a></div>`}
function stats(){const s=store.stats();$('[data-stat="journeys"]').textContent=s.count;$('[data-stat="distance"]').textContent=km(s.distance);$('[data-stat="time"]').textContent=mins(s.minutes);$('[data-stat="stops"]').textContent=s.stops}
function journeyRows(){const rows=store.completed(),host=$('[data-journey-list]');if(!rows.length){host.innerHTML='<div class="abh-map-empty"><strong>Your map is ready.</strong>Completed journeys will build your Adventure World here.</div>';return}host.innerHTML=rows.slice(0,12).map(a=>`<button class="abh-journey-row" type="button" data-open-adventure="${esc(a.id)}"><span>${icon(a.type)}</span><span><strong>${esc(a.title)}</strong><small>${niceDate(a.date)} · ${esc(a.startName)} → ${esc(a.endName)}</small></span><b>${a.distanceKm?km(a.distanceKm):label(a.type)}</b></button>`).join('')}
function plannedRows(){const rows=store.planned(),host=$('[data-planned-list]');if(!rows.length){host.innerHTML='<div class="abh-empty compact">No saved or upcoming plans yet. <a class="abh-text-btn" href="adventure-finder.html">Find your next adventure</a></div>';return}host.innerHTML=rows.slice(0,6).map(a=>`<article class="abh-plan-row"><span>${icon(a.type)}</span><div><strong>${esc(a.title)}</strong><small>${niceDate(a.date)} · ${esc(a.startName)} → ${esc(a.endName)}</small></div><div class="abh-row-actions"><a class="abh-btn small" href="${a.source==='walking'?'walking-hiking.html':a.source==='paddle'?'paddling.html':'trip-planner.html'}">Open</a></div></article>`).join('')}
function openJourney(id){const a=store.completed().find(x=>String(x.id)===String(id));if(!a)return;document.querySelectorAll('[data-open-adventure]').forEach(x=>x.classList.toggle('is-active',x.dataset.openAdventure===String(id)));window.AdventureHubMap?.select(id);const dialog=$('[data-adventure-dialog]'),c=$('[data-dialog-content]');c.innerHTML=`<div class="abh-dialog-hero"><span>${icon(a.type)}</span><div><p class="abh-kicker">Completed adventure</p><h2>${esc(a.title)}</h2><p>${niceDate(a.date)} · ${esc(label(a.type))}</p></div></div><div class="abh-route-summary"><div class="abh-route-point"><small>Started</small><strong>${esc(a.startName||'Start')}</strong></div><div class="abh-route-arrow">→</div><div class="abh-route-point"><small>Finished</small><strong>${esc(a.endName||'Finish')}</strong></div></div><div class="abh-dialog-stats"><div><small>Distance</small><strong>${a.distanceKm?km(a.distanceKm):'Not recorded'}</strong></div><div><small>Travel time</small><strong>${a.travelMinutes?mins(a.travelMinutes):'Not recorded'}</strong></div><div><small>Adventure duration</small><strong>${a.days?`${a.days} day${a.days===1?'':'s'}`:a.adventureMinutes?mins(a.adventureMinutes):'Not recorded'}</strong></div><div><small>Stops</small><strong>${a.stops||0}</strong></div><div><small>Completed</small><strong>${niceDate(a.date)}</strong></div><div><small>Route</small><strong>${(a.routePoints||[]).length>1?'Recorded':'Pin only'}</strong></div></div><div class="abh-dialog-foot"><a class="abh-btn" href="journal.html">Open Journal</a><button class="abh-btn primary" type="button" data-dialog-close>Done</button></div>`;dialog.showModal?.()}
root.addEventListener('click',e=>{const b=e.target.closest('[data-open-adventure]');if(b)openJourney(b.dataset.openAdventure)});window.addEventListener('adventurehub:open',e=>openJourney(e.detail?.id));
$('[data-dialog-close]')?.addEventListener('click',()=>$("[data-adventure-dialog]")?.close());$('[data-adventure-dialog]')?.addEventListener('click',e=>{if(e.target===e.currentTarget)e.currentTarget.close()});
function render(){nextCard();stats();journeyRows();plannedRows();const done=store.completed();window.AdventureHubMap?.draw(done);$('[data-map-status]').textContent=done.length?`${done.length} completed adventure${done.length===1?'':'s'} on your world map.`:'Complete an adventure in Adventure Builder and its journey can appear here.'}
const mapHost=document.getElementById('adventure-hub-map');if(mapHost)window.AdventureHubMap?.init(mapHost,store.completed());
window.addEventListener('adventurebuilder:journey-completed',e=>{if(!e.detail)return;store.add({...e.detail,status:'completed'});render()});
render();
})();
