(() => {
'use strict';
const gate=document.getElementById('community-gate'),area=document.getElementById('community-members-area'),feed=document.getElementById('community-feed'),status=document.getElementById('community-status'),search=document.getElementById('community-search'),category=document.getElementById('community-category');
if(!gate||!area)return;
let rows=[]; const auth=()=>window.ADVENTURE_BUILDER_AUTH; const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function decodeBody(value){try{const x=JSON.parse(value||'{}');return typeof x==='object'?x:{text:value||''};}catch{return {text:value||''};}}
async function photoUrl(client,path){if(!path)return'';const {data}=await client.storage.from('story-photos').createSignedUrl(path,3600);return data?.signedUrl||'';}
function render(){const q=(search?.value||'').toLowerCase(),cat=(category?.value||'').toLowerCase();const visible=rows.filter(x=>(!q||`${x.title} ${x.location} ${x.authorName} ${x.text}`.toLowerCase().includes(q))&&(!cat||x.category.toLowerCase()===cat));feed.innerHTML=visible.length?visible.map(x=>`<article class="website-community-card">${x.photo?`<img src="${esc(x.photo)}" alt="Adventure photograph from ${esc(x.location)}" loading="lazy">`:''}<div><div class="community-card-meta"><span>${esc(x.category)}</span><span>${esc(x.location)}</span></div><h3>${esc(x.title)}</h3><p>${esc(x.text)}</p><footer><strong>${esc(x.authorName)}</strong><time>${esc(x.date)}</time></footer><a class="text-link" href="${esc((window.ADVENTURE_BUILDER_CONFIG?.APP_URL||'https://app.adventurebuilder.co.uk'))}" target="_blank" rel="noopener">Open Community in App →</a></div></article>`).join(''):'<div class="empty-feature-state"><span>📷</span><h3>No matching adventures yet</h3><p>Post an adventure through the app or change the filters.</p></div>';status.textContent=`Showing ${visible.length} private community adventure${visible.length===1?'':'s'}.`;}
async function load(user,client){if(!user||!client){gate.hidden=false;area.hidden=true;return;}gate.hidden=true;area.hidden=false;status.textContent='Loading private community adventures…';const {data,error}=await client.from('stories').select('id,user_id,author_name,location,title,body,visibility,photo_path,created_at').eq('visibility','public').order('created_at',{ascending:false}).limit(60);if(error){status.textContent=`Community could not load: ${error.message}`;feed.innerHTML='<div class="empty-feature-state"><span>⚙️</span><h3>Community setup needed</h3><p>The website is connected to the app community tables, but Supabase permissions must allow signed-in members to read public community stories.</p></div>';return;}rows=await Promise.all((data||[]).map(async r=>{const b=decodeBody(r.body);return {title:r.title||'Adventure',location:r.location||'',authorName:r.author_name||'Adventure Builder member',text:b.text||'',category:b.category||'Other',date:new Date(r.created_at).toLocaleDateString('en-GB',{dateStyle:'medium'}),photo:await photoUrl(client,r.photo_path)}}));render();}
function sync(detail){load(detail?.user,detail?.client);}
window.addEventListener('adventurebuilder:auth',e=>sync(e.detail));document.getElementById('community-refresh')?.addEventListener('click',()=>{const a=auth();load(a?.getSession()?.user,a?.client)});search?.addEventListener('input',render);category?.addEventListener('change',render);setTimeout(()=>{const a=auth();load(a?.getSession()?.user,a?.client)},0);
})();
