(() => {
'use strict';
const PLAN_KEY='ab-paddle-plans-v2', DRAFT_KEY='ab-paddle-draft-v2', CHECK_KEY='ab-paddle-checklist-v2';
const form=document.querySelector('[data-paddle-trip-form]'); if(!form) return;
const q=s=>document.querySelector(s), qa=s=>[...document.querySelectorAll(s)];
const safeRead=(k,f)=>{try{const v=JSON.parse(localStorage.getItem(k));return v??f}catch{return f}};
const safeWrite=(k,v)=>{try{localStorage.setItem(k,JSON.stringify(v));return true}catch{return false}};
const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
const getTrip=()=>Object.fromEntries(new FormData(form));
const extra=()=>({name:q('[data-float-name]')?.value||'',contact:q('[data-float-contact]')?.value||'',vehicle:q('[data-float-vehicle]')?.value||'',floatNotes:q('[data-float-notes]')?.value||''});
function checklist(){return qa('[data-paddle-checklist] input').map(x=>({value:x.value,checked:x.checked}));}
function draft(){return {...getTrip(),...extra(),checklist:checklist(),wind:q('[data-paddle-wind]')?.value||'',gust:q('[data-paddle-gust]')?.value||'',offshore:!!q('[data-paddle-offshore]')?.checked,tide:!!q('[data-paddle-tide]')?.checked,waterTemp:!!q('[data-paddle-water-temp]')?.checked};}
function setValue(name,val){const el=form.elements[name];if(el&&val!==undefined&&val!==null)el.value=val;}
function loadDraft(d){if(!d)return;['activity','waterType','date','title','launchPoint','returnPoint','launchLat','launchLon','returnLat','returnLon','launchTime','backTime','distance','groupSize','routeNotes'].forEach(k=>setValue(k,d[k])); if(q('[data-float-name]'))q('[data-float-name]').value=d.name||'';if(q('[data-float-contact]'))q('[data-float-contact]').value=d.contact||'';if(q('[data-float-vehicle]'))q('[data-float-vehicle]').value=d.vehicle||'';if(q('[data-float-notes]'))q('[data-float-notes]').value=d.floatNotes||''; if(q('[data-paddle-wind]'))q('[data-paddle-wind]').value=d.wind??5;if(q('[data-paddle-gust]'))q('[data-paddle-gust]').value=d.gust??8;if(q('[data-paddle-offshore]'))q('[data-paddle-offshore]').checked=!!d.offshore;if(q('[data-paddle-tide]'))q('[data-paddle-tide]').checked=!!d.tide;if(q('[data-paddle-water-temp]'))q('[data-paddle-water-temp]').checked=!!d.waterTemp; if(Array.isArray(d.checklist)){const map=Object.fromEntries(d.checklist.map(x=>[x.value,x.checked]));qa('[data-paddle-checklist] input').forEach(x=>x.checked=!!map[x.value]);} updateMapLinks();assess();updateChecklist();updatePreview();}
function coords(which){return {lat:Number(form.elements[which+'Lat']?.value),lon:Number(form.elements[which+'Lon']?.value)};}
function updateMapLinks(){['launch','return'].forEach(which=>{const a=q(`[data-map-link="${which}"]`),c=coords(which);if(!a)return;if(Number.isFinite(c.lat)&&Number.isFinite(c.lon)&&c.lat&&c.lon){a.href=`https://www.openstreetmap.org/?mlat=${encodeURIComponent(c.lat)}&mlon=${encodeURIComponent(c.lon)}#map=15/${encodeURIComponent(c.lat)}/${encodeURIComponent(c.lon)}`;a.classList.remove('disabled');a.setAttribute('aria-disabled','false');}else{a.removeAttribute('href');a.classList.add('disabled');a.setAttribute('aria-disabled','true');}})}
function useLocation(which){const status=q('[data-location-status]');if(!navigator.geolocation){if(status)status.textContent='Location is not available in this browser.';return;}if(status)status.textContent='Getting your location…';navigator.geolocation.getCurrentPosition(pos=>{const lat=pos.coords.latitude.toFixed(6),lon=pos.coords.longitude.toFixed(6);setValue(which+'Lat',lat);setValue(which+'Lon',lon);const point=which==='launch'?'launchPoint':'returnPoint';if(!form.elements[point].value)form.elements[point].value=`GPS: ${lat}, ${lon}`;updateMapLinks();persist();updatePreview();if(status)status.textContent=`${which==='launch'?'Launch':'Return'} location saved.`;},()=>{if(status)status.textContent='Could not get your location. Check browser location permission.';},{enableHighAccuracy:true,timeout:10000,maximumAge:30000});}
function assess(){const status=q('[data-paddle-status]');if(!status)return;const w=Number(q('[data-paddle-wind]')?.value)||0,g=Number(q('[data-paddle-gust]')?.value)||w,off=!!q('[data-paddle-offshore]')?.checked;status.classList.remove('caution','avoid');let title='Lower-risk inputs entered',copy='Keep checking local conditions, water temperature and your own ability before launching.';if(w>=12||g>=18||off){status.classList.add('caution');title='Use extra caution';copy='Wind, gusts or an offshore direction can make returning harder. Consider a sheltered route or postponing.';}if(w>=20||g>=25){status.classList.remove('caution');status.classList.add('avoid');title='Demanding wind entered';copy='These inputs may be unsuitable for many recreational paddlers. Consider postponing and use authoritative local guidance.';}status.querySelector('strong').innerHTML=`<span class="paddle-status-light"></span>${title}`;status.querySelector('p').textContent=copy;updatePreview();}
function updateChecklist(){const items=qa('[data-paddle-checklist] input'),n=items.filter(x=>x.checked).length;const out=q('[data-check-progress]');if(out)out.textContent=`${n} / ${items.length}`;safeWrite(CHECK_KEY,Object.fromEntries(items.map(x=>[x.value,x.checked])));updatePreview();}
function formatPlan(d=draft()){
 const checked=(d.checklist||[]).filter(x=>x.checked).map(x=>x.value);
 return `ADVENTURE BUILDER · PADDLE FLOAT PLAN\n\nAdventure: ${d.title||'—'}\nActivity: ${d.activity||'—'}\nWater type: ${d.waterType||'—'}\nDate: ${d.date||'—'}\nName: ${d.name||'—'}\nPeople: ${d.groupSize||'—'}\nLaunch point: ${d.launchPoint||'—'}${d.launchLat?` (${d.launchLat}, ${d.launchLon})`:''}\nReturn / exit: ${d.returnPoint||'—'}${d.returnLat?` (${d.returnLat}, ${d.returnLon})`:''}\nLaunch time: ${d.launchTime||'—'}\nExpected back: ${d.backTime||'—'}\nDistance: ${d.distance?d.distance+' km':'—'}\nTrusted contact: ${d.contact||'—'}\nVehicle / parking: ${d.vehicle||'—'}\nRoute notes: ${d.routeNotes||'—'}\nExtra notes: ${d.floatNotes||'—'}\n\nCONDITIONS ENTERED\nWind: ${d.wind||'—'} mph\nPeak gust: ${d.gust||'—'} mph\nOffshore / away from safe shore: ${d.offshore?'YES':'NO'}\nTide / flow checked: ${d.tide?'YES':'NO'}\nWater-temperature clothing checked: ${d.waterTemp?'YES':'NO'}\n\nPRE-LAUNCH CHECKS\n${checked.length?checked.map(x=>'✓ '+x).join('\n'):'No checklist items ticked yet.'}\n\nAdventure Builder is a planning aid. Recheck local conditions, restrictions and authoritative safety information before launch.`;
}
function updatePreview(){const p=q('[data-float-preview]');if(p)p.textContent=formatPlan();}
function persist(){safeWrite(DRAFT_KEY,draft());}
function renderSaved(){const wrap=q('[data-saved-plans]');if(!wrap)return;const plans=safeRead(PLAN_KEY,[]);if(!plans.length){wrap.innerHTML='<p class="paddle-muted">No saved plans yet.</p>';return;}wrap.innerHTML=plans.slice().reverse().map(p=>`<article class="paddle-saved-item"><div><h3>${esc(p.title||p.activity||'Water adventure')}</h3><p>${esc(p.date||'No date')} · ${esc(p.activity||'')} · ${esc(p.launchPoint||'Launch not set')}</p></div><div class="paddle-saved-actions"><button class="paddle-mini-btn" type="button" data-load-plan="${esc(p.id)}">Load</button><button class="paddle-mini-btn" type="button" data-delete-plan="${esc(p.id)}">Delete</button></div></article>`).join('');}
function savePlan(){const d=draft();d.id=Date.now().toString(36);d.savedAt=new Date().toISOString();const plans=safeRead(PLAN_KEY,[]);plans.push(d);safeWrite(PLAN_KEY,plans);safeWrite(DRAFT_KEY,d);renderSaved();const s=q('[data-plan-status]');if(s)s.textContent='Plan saved on this device.';}
async function copyPlan(){const text=formatPlan();const s=q('[data-plan-status]');try{await navigator.clipboard.writeText(text);if(s)s.textContent='Float plan copied.';}catch{const ta=document.createElement('textarea');ta.value=text;document.body.appendChild(ta);ta.select();document.execCommand('copy');ta.remove();if(s)s.textContent='Float plan copied.';}}
function downloadPlan(){const text=formatPlan(),blob=new Blob([text],{type:'text/plain;charset=utf-8'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=`adventure-builder-paddle-plan-${new Date().toISOString().slice(0,10)}.txt`;document.body.appendChild(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),1000);const s=q('[data-plan-status]');if(s)s.textContent='Float plan downloaded.';}
function resetPlan(){form.reset();form.elements.groupSize.value=1;q('[data-paddle-wind]').value=5;q('[data-paddle-gust]').value=8;q('[data-paddle-offshore]').checked=false;q('[data-paddle-tide]').checked=false;q('[data-paddle-water-temp]').checked=false;qa('[data-paddle-checklist] input').forEach(x=>x.checked=false);['[data-float-name]','[data-float-contact]','[data-float-vehicle]','[data-float-notes]'].forEach(s=>{if(q(s))q(s).value='';});localStorage.removeItem(DRAFT_KEY);updateMapLinks();assess();updateChecklist();updatePreview();q('[data-plan-status]').textContent='New blank plan ready.';window.scrollTo({top:q('#paddle-planner')?.offsetTop||0,behavior:'smooth'});}

q('[data-scroll-planner]')?.addEventListener('click',()=>q('#paddle-planner')?.scrollIntoView({behavior:'smooth'}));
qa('[data-use-location]').forEach(b=>b.addEventListener('click',()=>useLocation(b.dataset.useLocation)));
form.addEventListener('input',()=>{updateMapLinks();persist();updatePreview();});
['[data-float-name]','[data-float-contact]','[data-float-vehicle]','[data-float-notes]'].forEach(s=>q(s)?.addEventListener('input',()=>{persist();updatePreview();}));
['[data-paddle-wind]','[data-paddle-gust]','[data-paddle-offshore]','[data-paddle-tide]','[data-paddle-water-temp]'].forEach(s=>q(s)?.addEventListener('input',()=>{assess();persist();}));
qa('[data-paddle-checklist] input').forEach(x=>x.addEventListener('change',()=>{updateChecklist();persist();}));
q('[data-save-plan]')?.addEventListener('click',savePlan);q('[data-copy-plan]')?.addEventListener('click',copyPlan);q('[data-download-plan]')?.addEventListener('click',downloadPlan);q('[data-new-plan]')?.addEventListener('click',resetPlan);
q('[data-saved-plans]')?.addEventListener('click',e=>{const load=e.target.dataset.loadPlan,del=e.target.dataset.deletePlan;if(load){const p=safeRead(PLAN_KEY,[]).find(x=>x.id===load);if(p){loadDraft(p);safeWrite(DRAFT_KEY,p);q('[data-plan-status]').textContent='Saved plan loaded.';window.scrollTo({top:q('#paddle-planner')?.offsetTop||0,behavior:'smooth'});}}if(del){safeWrite(PLAN_KEY,safeRead(PLAN_KEY,[]).filter(x=>x.id!==del));renderSaved();}});
const checkSaved=safeRead(CHECK_KEY,{});qa('[data-paddle-checklist] input').forEach(x=>x.checked=!!checkSaved[x.value]);
const existing=safeRead(DRAFT_KEY,null);if(existing)loadDraft(existing);else{const date=form.elements.date;if(date&&!date.value)date.value=new Date().toISOString().slice(0,10);updateChecklist();assess();updatePreview();}
renderSaved();
})();
