(() => {
'use strict';
const gate=document.getElementById('studio-gate'),area=document.getElementById('studio-members-area');if(!gate||!area)return;
const input=document.getElementById('studio-media'),timeline=document.getElementById('studio-timeline'),preview=document.getElementById('studio-preview'),status=document.getElementById('studio-status');let items=[];
const updateGate=(user)=>{gate.hidden=!!user;area.hidden=!user;};window.addEventListener('adventurebuilder:auth',e=>updateGate(e.detail?.user));setTimeout(()=>updateGate(window.ADVENTURE_BUILDER_AUTH?.getSession()?.user),0);
function render(){timeline.innerHTML=items.length?items.map((x,i)=>`<button class="studio-clip" type="button" data-index="${i}">${x.type.startsWith('video')?'🎥':'🖼️'}<span>${x.name}</span><small>${(x.size/1024/1024).toFixed(1)} MB</small><b data-remove="${i}" aria-label="Remove">×</b></button>`).join(''):'<p>No media added yet.</p>';status.textContent=items.length?`${items.length} item${items.length===1?'':'s'} in this project.`:'Add media to begin.';}
function show(i){const x=items[i];if(!x)return;preview.innerHTML=x.type.startsWith('video')?`<video src="${x.url}" controls playsinline></video>`:`<img src="${x.url}" alt="${x.name}">`;}
input?.addEventListener('change',()=>{for(const f of input.files||[]){items.push({name:f.name,type:f.type,size:f.size,url:URL.createObjectURL(f)});}render();if(items.length)show(items.length-1);input.value='';});
timeline?.addEventListener('click',e=>{const remove=e.target.closest('[data-remove]');if(remove){e.stopPropagation();const i=Number(remove.dataset.remove);URL.revokeObjectURL(items[i]?.url);items.splice(i,1);render();if(items.length)show(0);else preview.innerHTML='<div><span>🎞️</span><strong>Your preview appears here</strong><small>Select a photo or video from the timeline.</small></div>';return;}const clip=e.target.closest('[data-index]');if(clip)show(Number(clip.dataset.index));});
function project(){return {id:`studio-${Date.now()}`,name:document.getElementById('studio-project-name').value.trim()||'Adventure Studio project',format:document.getElementById('studio-format').value,title:document.getElementById('studio-title').value.trim(),caption:document.getElementById('studio-caption').value.trim(),media:items.map(({name,type,size})=>({name,type,size})),updatedAt:new Date().toISOString()};}
document.getElementById('studio-save')?.addEventListener('click',()=>{localStorage.setItem('adventureBuilderStudioProject',JSON.stringify(project()));status.textContent='Project plan saved in this browser. Cloud project sync is prepared for a later Studio stage.';});
document.getElementById('studio-export')?.addEventListener('click',()=>{const blob=new Blob([JSON.stringify(project(),null,2)],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='adventure-studio-project.json';a.click();setTimeout(()=>URL.revokeObjectURL(a.href),500);status.textContent='Project plan exported. Full video rendering will be added as the Studio develops.';});
document.getElementById('studio-clear')?.addEventListener('click',()=>{items.forEach(x=>URL.revokeObjectURL(x.url));items=[];render();preview.innerHTML='<div><span>🎞️</span><strong>Your preview appears here</strong><small>Select a photo or video from the timeline.</small></div>';});render();
})();
