-- Adventure Builder W56 — Account & Personalisation Foundation
-- Run once in the Supabase SQL editor.
-- Website + future app use the same authenticated profile rows and aggregate account counter.

create table if not exists public.adventure_profiles (
  user_id uuid primary key references auth.users(id) on delete cascade,
  profile_version integer not null default 1,
  age_band text null check (age_band in ('under18','18-24','25-39','40-54','55-69','70plus')),
  atmosphere text null check (atmosphere in ('quiet','balanced','lively')),
  pace text null check (pace in ('relaxed','balanced','active','challenging')),
  company text null check (company in ('solo','couple','family','friends')),
  interests jsonb not null default '[]'::jsonb,
  personalisation_enabled boolean not null default true,
  accessibility_sync_enabled boolean not null default false,
  accessibility_consent_at timestamptz null,
  accessibility_profile jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint accessibility_consent_required check (
    accessibility_sync_enabled = false
    or accessibility_consent_at is not null
  ),
  constraint no_accessibility_without_consent check (
    accessibility_sync_enabled = true
    or accessibility_profile = '{}'::jsonb
  )
);

alter table public.adventure_profiles enable row level security;

drop policy if exists "Users read own adventure profile" on public.adventure_profiles;
create policy "Users read own adventure profile"
on public.adventure_profiles for select
to authenticated
using (auth.uid() = user_id);

drop policy if exists "Users insert own adventure profile" on public.adventure_profiles;
create policy "Users insert own adventure profile"
on public.adventure_profiles for insert
to authenticated
with check (auth.uid() = user_id);

drop policy if exists "Users update own adventure profile" on public.adventure_profiles;
create policy "Users update own adventure profile"
on public.adventure_profiles for update
to authenticated
using (auth.uid() = user_id)
with check (auth.uid() = user_id);

drop policy if exists "Users delete own adventure profile" on public.adventure_profiles;
create policy "Users delete own adventure profile"
on public.adventure_profiles for delete
to authenticated
using (auth.uid() = user_id);

create table if not exists public.adventure_feedback (
  id bigint generated by default as identity primary key,
  user_id uuid null references auth.users(id) on delete set null,
  category text not null check (category in ('bug','idea','accessibility','general')),
  message text not null check (char_length(message) between 5 and 3000),
  page text null,
  source_url text null,
  reply_email text null,
  status text not null default 'new' check (status in ('new','reviewing','closed')),
  created_at timestamptz not null default now()
);

alter table public.adventure_feedback enable row level security;
-- No direct browser policies: feedback is submitted only through the validated RPC below.

create or replace function public.submit_adventure_feedback(
  p_category text,
  p_message text,
  p_page text default null,
  p_url text default null,
  p_reply_email text default null
) returns bigint
language plpgsql
security definer
set search_path = public, auth
as $$
declare
  v_id bigint;
begin
  if p_category not in ('bug','idea','accessibility','general') then
    raise exception 'Invalid feedback category';
  end if;
  if p_message is null or char_length(trim(p_message)) < 5 or char_length(p_message) > 3000 then
    raise exception 'Feedback message must be between 5 and 3000 characters';
  end if;
  if p_page is not null and char_length(p_page) > 120 then raise exception 'Invalid page'; end if;
  if p_url is not null and char_length(p_url) > 500 then raise exception 'Invalid URL'; end if;
  if p_reply_email is not null and char_length(p_reply_email) > 254 then raise exception 'Invalid email'; end if;

  insert into public.adventure_feedback(user_id,category,message,page,source_url,reply_email)
  values (auth.uid(),p_category,trim(p_message),nullif(trim(p_page),''),nullif(trim(p_url),''),nullif(trim(p_reply_email),''))
  returning id into v_id;
  return v_id;
end;
$$;
revoke all on function public.submit_adventure_feedback(text,text,text,text,text) from public;
grant execute on function public.submit_adventure_feedback(text,text,text,text,text) to anon, authenticated;

create or replace function public.get_adventure_builder_stats()
returns table(registered_users bigint)
language sql
security definer
set search_path = public, auth
as $$
  select count(*)::bigint from auth.users where email_confirmed_at is not null;
$$;
revoke all on function public.get_adventure_builder_stats() from public;
grant execute on function public.get_adventure_builder_stats() to anon, authenticated;

-- Optional cleanup after W56 has been deployed and confirmed working:
-- drop function if exists public.record_website_visit(text,text);
-- drop table if exists public.website_visits;
