(() => {
'use strict';
const rasterStyle={version:8,sources:{osm:{type:'raster',tiles:['https://tile.openstreetmap.org/{z}/{x}/{y}.png'],tileSize:256,attribution:'© OpenStreetMap contributors'}},layers:[{id:'osm',type:'raster',source:'osm'}]};
let map=null,ready=false,pending=[];
function feature(a){return {type:'Feature',properties:{id:a.id,title:a.title,type:a.type,location:a.location||''},geometry:{type:'Point',coordinates:[Number(a.lon),Number(a.lat)]}}}
function data(rows){return {type:'FeatureCollection',features:rows.filter(a=>Number.isFinite(Number(a.lat))&&Number.isFinite(Number(a.lon))&&Number(a.lat)&&Number(a.lon)).map(feature)}}
function draw(rows){pending=rows||[];if(!map||!ready)return;const gj=data(pending),src=map.getSource('hub-points');if(src)src.setData(gj);if(!gj.features.length)return;const bounds=gj.features.reduce((b,f)=>b.extend(f.geometry.coordinates),new maplibregl.LngLatBounds(gj.features[0].geometry.coordinates,gj.features[0].geometry.coordinates));map.fitBounds(bounds,{padding:70,maxZoom:12,duration:500})}
function init(container,rows=[]){if(map){draw(rows);return map}if(!container||typeof maplibregl==='undefined')return null;pending=rows;map=new maplibregl.Map({container,style:rasterStyle,center:[-3.2,54.8],zoom:4.4,minZoom:3.5,maxZoom:17});map.addControl(new maplibregl.NavigationControl({showCompass:false}),'top-right');map.addControl(new maplibregl.ScaleControl({unit:'imperial'}));map.on('load',()=>{ready=true;map.addSource('hub-points',{type:'geojson',data:data(pending),cluster:true,clusterMaxZoom:12,clusterRadius:42});map.addLayer({id:'hub-clusters',type:'circle',source:'hub-points',filter:['has','point_count'],paint:{'circle-color':'#f08a35','circle-radius':['step',['get','point_count'],18,10,23,30,29],'circle-stroke-color':'#ffffff','circle-stroke-width':2}});map.addLayer({id:'hub-cluster-count',type:'symbol',source:'hub-points',filter:['has','point_count'],layout:{'text-field':['get','point_count_abbreviated'],'text-size':12},paint:{'text-color':'#151515'}});map.addLayer({id:'hub-point',type:'circle',source:'hub-points',filter:['!',['has','point_count']],paint:{'circle-color':'#f08a35','circle-radius':9,'circle-stroke-color':'#fff','circle-stroke-width':3}});map.on('click','hub-clusters',async e=>{const f=e.features?.[0],src=map.getSource('hub-points');if(!f||!src)return;const z=await src.getClusterExpansionZoom(f.properties.cluster_id);map.easeTo({center:f.geometry.coordinates,zoom:z})});map.on('click','hub-point',e=>{const f=e.features?.[0];if(!f)return;window.dispatchEvent(new CustomEvent('adventurehub:open',{detail:{id:f.properties.id}}));});['hub-clusters','hub-point'].forEach(layer=>{map.on('mouseenter',layer,()=>map.getCanvas().style.cursor='pointer');map.on('mouseleave',layer,()=>map.getCanvas().style.cursor='')});draw(pending)});return map}
function resize(){map?.resize()}
window.AdventureHubMap={init,draw,resize,_data:data};
})();
