(() => {
'use strict';
const root=document.querySelector('[data-adventure-hub]'),store=window.AdventureHubStore;if(!root||!store)return;
const $=(s,c=root)=>c.querySelector(s), $$=(s,c=root)=>[...c.querySelectorAll(s)], esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const meta={hike:['🥾','Hike'],cycle:['🚴','Cycle'],road:['🚐','Road Trip'],camp:['🏕️','Camping'],paddle:['🏄','Paddleboard'],kayak:['🛶','Kayak'],photo:['📸','Photography'],explore:['🧭','Explore'],dog:['🐕','Dog Walk'],fishing:['🎣','Fishing']};
const icon=t=>meta[t]?.[0]||'🌍',label=t=>meta[t]?.[1]||'Adventure';
const distance=n=>{n=Number(n)||0;return n?`${n.toFixed(n<10?1:0)} km`:'Distance not recorded'};
const niceDate=s=>{if(!s)return'No date';const d=new Date(`${String(s).slice(0,10)}T12:00:00`);return Number.isNaN(d)?s:d.toLocaleDateString('en-GB',{day:'numeric',month:'short',year:'numeric'})};
function tab(name){$$('[data-hub-tab]').forEach(b=>b.classList.toggle('is-active',b.dataset.hubTab===name));$$('[data-hub-view]').forEach(v=>v.hidden=v.dataset.hubView!==name);if(name==='map'){setTimeout(()=>{renderMap();window.AdventureHubMap?.resize()},30)}}
$$('[data-hub-tab]').forEach(b=>b.addEventListener('click',()=>tab(b.dataset.hubTab)));
function empty(kind='feed'){const add='<button type="button" class="abh-btn primary" data-open-tab="add">Add or import an adventure</button>';return `<div class="abh-empty"><span>${kind==='timeline'?'📅':'🧭'}</span><h3>Your story starts with one adventure.</h3><p>Import something you already planned in Adventure Builder, or add a completed adventure manually.</p><div>${add}<a class="abh-btn" href="walking-hiking.html">Plan a walk</a></div></div>`}
function mini(a){return `<button class="abh-mini" type="button" data-open-adventure="${esc(a.id)}"><span class="abh-mini-icon">${icon(a.type)}</span><span><strong>${esc(a.title)}</strong><small>${niceDate(a.date)}${a.location?` · ${esc(a.location)}`:''}</small></span><b>${a.distanceKm?distance(a.distanceKm):label(a.type)}</b></button>`}
function card(a){return `<article class="abh-adventure-card" data-card-type="${esc(a.type)}"><div class="abh-card-cover"><span>${icon(a.type)}</span><small>${esc(label(a.type))}</small></div><div class="abh-adventure-body"><div class="abh-adventure-title"><div><h3>${esc(a.title)}</h3><p>${niceDate(a.date)}${a.location?` · ${esc(a.location)}`:''}</p></div>${a.newPlace?'<span class="abh-new-place">New place</span>':''}</div><div class="abh-chips">${a.distanceKm?`<span>📍 ${distance(a.distanceKm)}</span>`:''}${a.photos?`<span>📸 ${a.photos}</span>`:''}${a.durationMinutes?`<span>⏱ ${Math.round(a.durationMinutes)} min</span>`:''}${a.nights?`<span>🌙 ${a.nights} night${a.nights===1?'':'s'}</span>`:''}${a.lat&&a.lon?'<span>🗺 Mapped</span>':''}</div>${a.notes?`<p class="abh-card-note">${esc(a.notes.slice(0,170))}${a.notes.length>170?'…':''}</p>`:''}<div class="abh-card-actions"><button type="button" class="abh-btn small" data-open-adventure="${esc(a.id)}">Relive</button><button type="button" class="abh-text-btn danger" data-remove-adventure="${esc(a.id)}">Remove</button></div></div></article>`}
function render(){const rows=store.all(),s=store.stats();$('[data-stat="count"]').textContent=s.count;$('[data-stat="distance"]').textContent=`${s.distance.toFixed(s.distance<10?1:0)} km`;$('[data-stat="places"]').textContent=s.places;$('[data-stat="photos"]').textContent=s.photos;
 const recent=$('[data-recent-adventures]');recent.innerHTML=rows.length?rows.slice(0,4).map(mini).join(''):empty();
 $('[data-milestones]').innerHTML=store.milestones().map(m=>`<div class="abh-milestone ${m.done?'done':''}"><span>${m.icon}</span><div><strong>${esc(m.name)}</strong><small>${esc(m.copy)}</small></div><b>${m.done?'✓':'○'}</b></div>`).join('');renderFeed();renderTimeline();renderImports();renderMapList();window.AdventureHubMap?.draw(rows)}
function renderFeed(){let rows=store.all(),q=($('[data-feed-search]')?.value||'').trim().toLowerCase(),f=$('[data-feed-filter]')?.value||'all';if(f!=='all')rows=rows.filter(a=>a.type===f);if(q)rows=rows.filter(a=>[a.title,a.location,a.notes,label(a.type)].join(' ').toLowerCase().includes(q));$('[data-adventure-feed]').innerHTML=rows.length?rows.map(card).join(''):empty()}
$('[data-feed-search]')?.addEventListener('input',renderFeed);$('[data-feed-filter]')?.addEventListener('change',renderFeed);
function renderTimeline(){const rows=store.all(),wrap=$('[data-adventure-timeline]');if(!rows.length){wrap.innerHTML=empty('timeline');return}const groups={};rows.forEach(a=>{const d=new Date(`${a.date}T12:00:00`),k=Number.isNaN(d)?'Undated':d.toLocaleDateString('en-GB',{month:'long',year:'numeric'});(groups[k]??=[]).push(a)});wrap.innerHTML=Object.entries(groups).map(([month,list])=>`<section class="abh-month"><h3>${esc(month)}</h3><div>${list.map(a=>`<button type="button" data-open-adventure="${esc(a.id)}"><span>${icon(a.type)}</span><span><strong>${esc(a.title)}</strong><small>${a.location?esc(a.location):label(a.type)}</small></span><b>${a.distanceKm?distance(a.distanceKm):niceDate(a.date)}</b></button>`).join('')}</div></section>`).join('')}
function renderMap(){const el=document.getElementById('adventure-hub-map'),rows=store.all();window.AdventureHubMap?.init(el,rows);const mapped=rows.filter(a=>a.lat&&a.lon).length;$('[data-map-status]').textContent=mapped?`${mapped} mapped adventure${mapped===1?'':'s'}. Select a point to relive it.`:'No adventures have GPS coordinates yet. Import a saved walking/paddle route or use GPS when adding one.'}
function renderMapList(){const rows=store.all().filter(a=>a.lat&&a.lon);$('[data-map-list]').innerHTML=rows.length?rows.map(mini).join(''):'<div class="abh-empty compact"><p>No mapped adventures yet.</p></div>'}
function sourceLabel(s){return {'walking':'Walking & Hiking','trip-planner':'Trip Planner','paddle':'Paddle & Kayak','journal':'Adventure Journal'}[s]||'Adventure Builder'}
function renderImports(){const rows=store.imports(),wrap=$('[data-import-list]');wrap.innerHTML=rows.length?rows.map(a=>`<article class="abh-import"><span>${icon(a.type)}</span><div><strong>${esc(a.title)}</strong><small>${sourceLabel(a.source)} · ${niceDate(a.date)}${a.location?` · ${esc(a.location)}`:''}</small></div><button class="abh-btn small" type="button" data-import-source="${esc(a.source)}" data-import-id="${esc(a.sourceId)}">Import</button></article>`).join(''):'<div class="abh-empty compact"><span>✓</span><p>Nothing new to import from this device.</p></div>'}
$('[data-refresh-imports]')?.addEventListener('click',renderImports);
const form=$('[data-adventure-form]'),typeSelect=$('[data-activity-type]');
function fields(){const t=typeSelect.value;$('[data-field-group="trip"]').hidden=!['road','camp'].includes(t);$('[data-field-group="water"]').hidden=!['paddle','kayak'].includes(t);$('[data-field-group="fishing"]').hidden=t!=='fishing';$('[data-field-group="distance"]').hidden=t==='photo'||t==='camp'||t==='fishing';$('[data-field="elevation"]').hidden=!['hike','cycle'].includes(t)}
typeSelect?.addEventListener('change',fields);fields();if(form?.elements.date)form.elements.date.value=new Date().toISOString().slice(0,10);
$('[data-use-location]')?.addEventListener('click',()=>{const st=$('[data-location-status]');if(!navigator.geolocation){st.textContent='GPS is not available in this browser.';return}st.textContent='Getting location…';navigator.geolocation.getCurrentPosition(pos=>{form.elements.lat.value=pos.coords.latitude.toFixed(6);form.elements.lon.value=pos.coords.longitude.toFixed(6);if(!form.elements.location.value)form.elements.location.value=`GPS ${Number(pos.coords.latitude).toFixed(4)}, ${Number(pos.coords.longitude).toFixed(4)}`;st.textContent='GPS position saved for your Adventure Map.'},()=>st.textContent='Location permission was not available.',{enableHighAccuracy:true,timeout:10000,maximumAge:30000})});
form?.addEventListener('submit',e=>{e.preventDefault();const d=Object.fromEntries(new FormData(form).entries());d.newPlace=form.elements.newPlace.checked;store.add(d);form.reset();form.elements.date.value=new Date().toISOString().slice(0,10);form.elements.type.value='hike';fields();$('[data-form-status]').textContent='Adventure added. It is now part of your Hub timeline.';render();tab('dashboard')});
function openAdventure(id){const a=store.all().find(x=>x.id===id),dlg=$('[data-adventure-dialog]',document);if(!a||!dlg)return;const details=[a.distanceKm&&['Distance',distance(a.distanceKm)],a.durationMinutes&&['Time outdoors',`${Math.round(a.durationMinutes)} min`],a.elevationM&&['Elevation / high point',`${Math.round(a.elevationM)} m`],a.days&&['Days',a.days],a.nights&&['Nights',a.nights],a.photos&&['Photos',a.photos],a.waterType&&['Water',a.waterType],a.species&&['Species / focus',a.species]].filter(Boolean);$('[data-dialog-content]',dlg).innerHTML=`<div class="abh-dialog-hero"><span>${icon(a.type)}</span><div><p class="abh-kicker">Relive adventure</p><h2>${esc(a.title)}</h2><p>${niceDate(a.date)}${a.location?` · ${esc(a.location)}`:''}</p></div></div><div class="abh-dialog-stats">${details.map(([k,v])=>`<div><small>${esc(k)}</small><strong>${esc(v)}</strong></div>`).join('')}</div>${a.notes?`<div class="abh-dialog-story"><h3>The memory</h3><p>${esc(a.notes)}</p></div>`:''}<div class="abh-dialog-timeline"><div><b>🚀 Adventure started</b><small>${niceDate(a.date)}</small></div>${a.location?`<div><b>📍 ${esc(a.location)}</b><small>Place recorded</small></div>`:''}${a.photos?`<div><b>📸 ${a.photos} photo${a.photos===1?'':'s'}</b><small>Memories captured</small></div>`:''}<div><b>🏅 Adventure complete</b><small>Added to your Adventure Hub</small></div></div>`;dlg.showModal?dlg.showModal():dlg.setAttribute('open','')}
$('[data-dialog-close]',document)?.addEventListener('click',()=>{const d=$('[data-adventure-dialog]',document);d.close?d.close():d.removeAttribute('open')});
root.addEventListener('click',e=>{const open=e.target.closest('[data-open-adventure]'),remove=e.target.closest('[data-remove-adventure]'),imp=e.target.closest('[data-import-source]'),opentab=e.target.closest('[data-open-tab]');if(open)openAdventure(open.dataset.openAdventure);if(remove&&confirm('Remove this adventure from the Hub?')){store.remove(remove.dataset.removeAdventure);render()}if(imp){store.importOne(imp.dataset.importSource,imp.dataset.importId);render()}if(opentab)tab(opentab.dataset.openTab)});
window.addEventListener('adventurehub:open',e=>openAdventure(e.detail?.id));render();
})();
